"""
Security Audit Agent — LLM scan for common vulnerabilities.

Covers OWASP Top 10 patterns: hardcoded secrets, injection risks,
unvalidated inputs, insecure deserialization, missing auth, weak crypto.

Uses the traversal model (cheap) in concurrent batches.
Output: docs/SECURITY_REPORT.md
"""
import asyncio
import logging

from config.llm_client import llm_call_async

logger = logging.getLogger("arkhe.security")

SYSTEM = """You are a security engineer doing a focused code security review.
For each file, identify ONLY real security issues — not style, not performance.

Look for:
- Hardcoded credentials, API keys, tokens, passwords
- SQL injection (string concatenation or f-strings in queries)
- Command injection (shell=True, os.system, subprocess with user input, eval, exec)
- Path traversal (user-controlled paths without sanitization)
- Unvalidated/unsanitized user inputs reaching dangerous sinks
- Missing authentication or authorization checks on sensitive routes/operations
- Insecure deserialization (pickle.loads, yaml.load without Loader=)
- Sensitive data in logs, error messages, or exception text
- Weak or broken cryptography (MD5/SHA1 for passwords, hardcoded IV/salt/key)
- Open redirects, SSRF, XXE patterns

Output format per finding:
  FILE: <path>
  SEVERITY: CRITICAL | HIGH | MEDIUM | LOW
  ISSUE: <one-line description>
  CODE: <relevant snippet, max 1 line>
  FIX: <one-line recommendation>

If a file has no issues, write: FILE: <path> — CLEAN
Be concise. Flag real issues only, not theoretical ones."""

BATCH_SIZE  = 4
MAX_CHARS   = 1200
_SKIP_PATHS = {"test", "docs", ".arkhe_cache", "_refactored", "tests_generated"}


def _should_audit(path: str) -> bool:
    return not any(seg in path for seg in _SKIP_PATHS)


def _build_prompt(batch: list[dict]) -> str:
    parts = []
    for f in batch:
        preview = f["content"][:MAX_CHARS]
        parts.append(f"### {f['path']}\n```\n{preview}\n```")
    return "\n\n".join(parts)


async def _audit_batch(batch: list[dict], idx: int, sem: asyncio.Semaphore) -> str:
    async with sem:
        prompt = _build_prompt(batch)
        return await llm_call_async("traversal", SYSTEM, prompt, max_tokens=1024)


async def run_security_audit(modules: list[dict]) -> str:
    source = [m for m in modules if _should_audit(m["path"]) and m.get("content", "").strip()]
    batches = [source[i:i + BATCH_SIZE] for i in range(0, len(source), BATCH_SIZE)]

    sem   = asyncio.Semaphore(3)
    tasks = [_audit_batch(b, i, sem) for i, b in enumerate(batches)]
    raw   = await asyncio.gather(*tasks, return_exceptions=True)

    sections = []
    for r in raw:
        if isinstance(r, Exception):
            logger.error(f"[security] batch failed: {r}")
        else:
            sections.append(r)

    if not sections:
        return "# Security Report\n\nAll batches failed — check your API key and rate limits.\n"

    return (
        "# Security Audit Report\n\n"
        "> Generated by Arkhe. Treat all findings as leads — "
        "verify manually before acting on them.\n\n"
        + "\n\n---\n\n".join(sections)
        + "\n"
    )
