"""
Security Audit Agent — LLM scan for common vulnerabilities.

Covers OWASP Top 10 patterns: hardcoded secrets, injection risks,
unvalidated inputs, insecure deserialization, missing auth, weak crypto.

Uses the traversal model (cheap) in concurrent batches.
Output: docs/SECURITY_REPORT.md
"""
import asyncio
import logging

from config.llm_client import llm_call_async

logger = logging.getLogger("arkhe.security")

SYSTEM = """You are a security engineer doing a focused code security review.
For each file, identify ONLY real security issues — not style, not performance.

Context: This codebase is a code analysis tool that intentionally reads repository files
and sends their contents to LLM APIs. Do NOT flag the tool's core design (passing file
contents to an LLM) as prompt injection — that is the tool's intended purpose.

Look for:
- Hardcoded credentials: literal string values assigned directly (e.g. api_key="sk-abc123"). Do NOT flag api_key=variable patterns where the variable comes from os.getenv() or a function parameter — those are NOT hardcoded.
- SQL injection (string concatenation or f-strings in queries)
- Command injection (shell=True, os.system, subprocess with user-controlled input, eval, exec on user input)
- Path traversal (user-supplied paths reaching os.path.join/open without validation against a safe root)
- Unvalidated inputs from HTTP requests reaching dangerous sinks (file system, shell, DB)
- Missing authentication or authorization on sensitive HTTP routes
- Insecure deserialization (pickle.loads, yaml.load without Loader=)
- Sensitive data (API keys, tokens, PII) written to logs or error messages
- Weak or broken cryptography (MD5/SHA1 for passwords, hardcoded IV/salt/key)
- Open redirects, SSRF (user-controlled URLs passed to requests/httpx without allow-list)

Output format — use EXACTLY this structure for every file, no exceptions:
  FILE: <path> — CLEAN
  or:
  FILE: <path>
  SEVERITY: CRITICAL | HIGH | MEDIUM | LOW
  ISSUE: <one-line description>
  CODE: <relevant snippet, max 1 line>
  FIX: <one-line recommendation>

Rules:
- Do NOT use markdown headers (###), numbered lists, or prose paragraphs — only the FILE/SEVERITY/ISSUE/CODE/FIX format.
- Do NOT change format mid-response.
- If a snippet appears truncated or ends mid-token, do NOT flag it — you cannot assess what you cannot see.
- subprocess.run() called with a list (not shell=True) is NOT command injection.
- os.path.join() on filenames from os.listdir() or a validated allowlist is NOT path traversal.
- Passing api_key from a variable (not a hardcoded string) to a client constructor is NOT a hardcoded credential.
Be concise. Flag real, exploitable issues only — not theoretical or intentional design choices."""

BATCH_SIZE  = 4
MAX_CHARS   = 3000
_SKIP_PATHS = {"test", "docs", ".arkhe_cache", "_refactored", "tests_generated"}


def _should_audit(path: str) -> bool:
    return not any(seg in path for seg in _SKIP_PATHS)


def _build_prompt(batch: list[dict]) -> str:
    parts = []
    for f in batch:
        preview = f["content"][:MAX_CHARS]
        parts.append(f"### {f['path']}\n```\n{preview}\n```")
    return "\n\n".join(parts)


async def _audit_batch(batch: list[dict], idx: int, sem: asyncio.Semaphore) -> str:
    async with sem:
        prompt = _build_prompt(batch)
        return await llm_call_async("traversal", SYSTEM, prompt, max_tokens=1024)


async def run_security_audit(modules: list[dict]) -> str:
    source = [m for m in modules if _should_audit(m["path"]) and m.get("content", "").strip()]
    batches = [source[i:i + BATCH_SIZE] for i in range(0, len(source), BATCH_SIZE)]

    sem   = asyncio.Semaphore(3)
    tasks = [_audit_batch(b, i, sem) for i, b in enumerate(batches)]
    raw   = await asyncio.gather(*tasks, return_exceptions=True)

    sections = []
    for r in raw:
        if isinstance(r, Exception):
            logger.error(f"[security] batch failed: {r}")
        else:
            sections.append(r)

    if not sections:
        return "# Security Report\n\nAll batches failed — check your API key and rate limits.\n"

    return (
        "# Security Audit Report\n\n"
        "> Generated by Arkhe. Treat all findings as leads — "
        "verify manually before acting on them.\n\n"
        + "\n\n---\n\n".join(sections)
        + "\n"
    )
